[project]
name = "slower"
version = "0.0.1"
authors = [
    { name="Hudson Cooperi", email="hncooper96@gmail.com" },
]
description = "Make things slower"
dependencies = []

[project.urls]
source = "https://github.com/hudson-ai/slower"
download = "https://pypi.org/project/slower/#files"
